In [1]:
#single line comment
'''multi-line
comment '''
import numpy as np

## Basic of numpy


In [2]:
a=np.array([5,6,7])#one dimensional array
print(a)

[5 6 7]


In [3]:
#dimension
b=np.array([[1,2,3],[4,5,6]],dtype=float)
print("2X3 matrix \n",b)
print("dimension of the array",b.ndim)#ndim fuction is used to  print dimenson of the array.

2X3 matrix 
 [[1. 2. 3.]
 [4. 5. 6.]]
dimension of the array 2


In [4]:
#shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [5]:
#data type
print(a.dtype)
print(b.dtype)

int32
float64


In [6]:
#size
print(a.itemsize)
print(b.itemsize)

4
8


In [7]:
#storage occupied
a.nbytes


12

## accessing/changing specific elements,rows,columns etc.

In [8]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
# a[row index,columns index] indexing start from zero

In [10]:
#get specific elements
a[0,1]#for getting 2 as output

2

In [11]:
#negative indexing
a[1,-1]#negative indexing start with 1 

10

In [12]:
#get row
print(a[1])
print(a[1,:])#: is use to select every element

[ 6  7  8  9 10]
[ 6  7  8  9 10]


In [13]:
#get columns
print(a[:,3])

[4 9]


In [14]:
#change the elements 
a[0,1]=12
print(a)

[[ 1 12  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
# to change column element
a[:,2]=11 #it will change the 3rd element of both the rows
a

array([[ 1, 12, 11,  4,  5],
       [ 6,  7, 11,  9, 10]])

In [16]:
#to change the row element
a[0,:]=[1,2,3,4,5]#it will change all the element of first row
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7, 11,  9, 10]])

## intializing different arrays

In [17]:
#all zeros matrics
a=np.zeros(4)#it creates array with with all the elements as zero and its data type is float
print(a)
print(a.dtype)

[0. 0. 0. 0.]
float64


In [18]:
#np.zeros(shape,dtype="values",order="c or r") c is for columns and r is for rows
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((4,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
#all ones matrix
np.ones(4)#it also creates data type of float

array([1., 1., 1., 1.])

In [21]:
#np.onez(shape,dtype="values",order="c or r") c is for columns and r is for rows
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# creating a matrix with same elements
#np.full(shape,element value,dtype="value")
np.full((3,4),4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [23]:
np.full_like(a,4)#full_like copies the dimension of the matrix |

array([4., 4., 4., 4.])

In [24]:
#random no matrix
#np.random.rand(shape)
np.random.rand(1,2)

array([[0.26409059, 0.44347594]])

In [25]:
np.random.random_sample(a.shape)#copies the dimension of matrix and fill it with random no

array([0.6587902 , 0.60568608, 0.02891565, 0.56013326])

In [26]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#stacking using repeation
arr=np.array([[1,2,3]])
a1=np.repeat(arr,2,axis=0)#axis=0 is for column wise axis=1 is for row wise
a1

array([[1, 2, 3],
       [1, 2, 3]])

## mathematics

In [28]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [29]:
a+5

array([6, 7, 8, 9])

In [30]:
a-5

array([-4, -3, -2, -1])

In [31]:
a*3

array([ 3,  6,  9, 12])

In [32]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [33]:
a//2 #use to get int output

array([0, 1, 1, 2], dtype=int32)

In [34]:
b=np.array([5,6,7,8])
b

array([5, 6, 7, 8])

In [35]:
a+b

array([ 6,  8, 10, 12])

In [36]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [37]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [38]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## linear algebra

In [39]:
a=np.full((3,4),5)
b=np.full((4,5),7)
print(a)
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [40]:
#matrix multiplication
np.matmul(a,b)

array([[140, 140, 140, 140, 140],
       [140, 140, 140, 140, 140],
       [140, 140, 140, 140, 140]])

In [41]:
#determinant
a=np.identity(3)
np.linalg.det(a)

1.0

## statistics

In [42]:
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
#to find minimum 
np.min(s,axis=1)#from a particular row or column

array([1, 4])

In [44]:
# to find maximun
print(np.max(s))#from whole matrix
print(np.max(s,axis=0))

6
[4 5 6]


In [45]:
#to find sum 
print(np.sum(s))
print(np.sum(s,axis=0))

21
[5 7 9]


## reorganizing array

In [46]:
b1=np.array([[3,5,7,1,3,4],[4,5,3,6,5,9]])
b1

array([[3, 5, 7, 1, 3, 4],
       [4, 5, 3, 6, 5, 9]])

In [47]:
#to reshape the matrix 
a1=b1.reshape((6,2))
a1

array([[3, 5],
       [7, 1],
       [3, 4],
       [4, 5],
       [3, 6],
       [5, 9]])

In [48]:
#vertical stacking
v1=np.array([2,3,4])
v2=np.array([5,6,7])
np.vstack([v1,v2])

array([[2, 3, 4],
       [5, 6, 7]])

In [49]:
#horizontal stacking
np.hstack([v1,v2])

array([2, 3, 4, 5, 6, 7])

In [50]:
#import data from a file
data=np.genfromtxt("testing.txt",delimiter=",")
data

array([[nan,  2., nan],
       [nan,  2., nan]])

## boolean masking and advanced indexing

In [51]:
data>15

array([[False, False, False],
       [False, False, False]])

In [52]:
a=np.array([1,2,3,4,5,6,7])
a[[2,4,5]]#to access specific element

array([3, 5, 6])

In [53]:
#to check condition for whole array
print(np.any(a>2))#to if any element in a is greater than 2

True


# python


In [54]:
#data types
int =1 #integer
float =1.2 #float
str ="hello" #string
bool =True #boolean

In [55]:
#variable
age="1500"#varibale is use to store values
print("my age is "+ age + " year")
print("my age is",age,"year") 
print(f"my age is {age} year")

my age is 1500 year
my age is 1500 year
my age is 1500 year


In [56]:
#string
print("my\nis thor")#\n is used for print in next line
print("to print \\")#\\ is used for print \
name="thor is hero"
print(name.lower())# to convert string in lower case
print(name.upper())#to convert string in lower case
print(name.islower())#islower is used to check whether all the character are in lower case
print(name.isupper())#islower is used to check whether all the character are in upper case
print(len(name))#to calculate the lenght of the string including <space>
print(name[1])#index works same as list in string
print(name[:2])#it will take all the element before 2
print(name[0:9:2])#use to skip 1 char
print(name.index("i"))#to find the index of the character/word in a string which occured 1st
print(name.replace("o","O"))#replace all character/word in a string

my
is thor
to print \
thor is hero
THOR IS HERO
True
False
12
h
th
to sh
5
thOr is herO


In [57]:
#number
print(5+9)#addition
print("5"+"9")#here 5 and 9 are treated as string + concatenate
print(3/8+5)#it uses BODMAS
print(5%2)#used for reminder
print(abs(-5))#to returns absolute
print(max(2,4,5,7,2))#to get maximum value
print(min(2,4,5,7,2))#to get minimum value
print(round(5.6))#to round off values

14
59
5.375
1
5
7
2
6


In [58]:
#to take input of user
a=input("enter anything ")#default format of input is string"
print(a)

enter anything hi there
hi there


In [59]:
#list
a=["hi","hello","a","b"]
print(a)
b=[1,"a",3,5,6]
print(b)
print(a[1])#indexing works same as string
print(a[1][1])
print(a[-1])
a[1]="there"
print(a[1])#update list using indexing
a.extend(b)#concatenate of list(here all the element will concatenated in a)
print(a)
b.append("after")#add the element in last 
print(b)
b.insert(1,"before")#to add a element at a particular position
print(b)
b.remove("after")#to remove the given element from list
print(b)
b.pop()#to remove the last element from the list
print(b)
print(b.index("before"))#to get the indexx of specific element
print(b.count(1))#to count the occurance of the element in the list
c=[1,2,4,5,6,4,8,9]
c.sort()#to sort the list in ascending order
print(c)
c.sort(reverse=True)#to sort the list in descending order
print(c)
d=c.copy()
print(d)


['hi', 'hello', 'a', 'b']
[1, 'a', 3, 5, 6]
hello
e
b
there
['hi', 'there', 'a', 'b', 1, 'a', 3, 5, 6]
[1, 'a', 3, 5, 6, 'after']
[1, 'before', 'a', 3, 5, 6, 'after']
[1, 'before', 'a', 3, 5, 6]
[1, 'before', 'a', 3, 5]
1
1
[1, 2, 4, 4, 5, 6, 8, 9]
[9, 8, 6, 5, 4, 4, 2, 1]
[9, 8, 6, 5, 4, 4, 2, 1]


In [60]:
#tuple(element can't be updated or removed)
a=(1,2)
print(a)

(1, 2)


In [61]:
#dictionaries(key value pair)
dic1={"a":[1,2,3],
      "b":[4,5,6]}
print(dic1)
print(dic1["a"])#key must be provided,indexing work same as string
print(dic1["a"][0])

{'a': [1, 2, 3], 'b': [4, 5, 6]}
[1, 2, 3]
1


In [62]:
#functions
def new_fun():#indentation is important in function
    print("hello")
new_fun()#function is been called
def new_fun(a,b):
    c=a+b
    print(c)
new_fun(1,2)

hello
3


In [63]:
#return statement(it is consider as last statement of the function)
def cube(a):
    return a*a*a#when we use return statement we don't need to print it
cube(2)

8

In [64]:
#operators
"""
= is used for assign of operator
== for comparison
>= smaller than equal to
<= greater than equal to
!= not equal to
and/& for and condition
|/or for or condition
"""

'\n= is used for assign of operator\n== for comparison\n>= smaller than equal to\n<= greater than equal to\n!= not equal to\nand/& for and condition\n|/or for or condition\n'

In [65]:
#if statement
def max1(a,b,c):
    if a>b and a>c:
        print("a is maximum")
    elif b>a and b>c:
        print("b is maximum")
    else:
        print("c is maximum")
max1(4,5,6)

c is maximum


In [66]:
#while loop
i=0
while i<=10:
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9
10


In [67]:
#for loop
name="for"
for i in name:
    print(i)
for i in range(1,10):
    print(i)
for i in range(len(name)):
    print(i)

f
o
r
1
2
3
4
5
6
7
8
9
0
1
2


In [68]:
#exponent function
def power(num,power):
    result=1
    for i in range(power):
        result=result*num
    return result
print(power(3,2))

9


In [69]:
#2d lists and nested loops
number=[[1,2,3],
       [4,5,6],
       [7,8,9]]
for i in number:
    for j in i:
        print(j)
print(number[0])
print(number[0][0])

1
2
3
4
5
6
7
8
9
[1, 2, 3]
1


In [70]:
#try and except
try:
    number=int(input("enter your number "))
except:
    print("please enter valid no") 

enter your number hk
please enter valid no


In [72]:
#reading file
file=open("testing.txt","r")#reading<"r">/append<"a">/write<"w"> in file
# file.write("hello")#used to write in file
print(file.read())#to read the file
print(file.readline())#to read first line 
file.close()#to close file

[1,2,3]
{1,2,3}

